[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
calibration = "https://api.calibration.node.glif.io/rpc/v1"
mainnet = "https://api.node.glif.io/rpc/v1"

[etherscan]
calibration = { key = "${FILSCAN_API_KEY}", chain = 314159, url = "https://calibration.filscan.io/api" }
mainnet = { key = "${FILSCAN_API_KEY}", chain = 314, url = "https://filscan.io/api" }
